#!/bin/bash
# Weekly ban summary report for fail2ban
# Generated by Ansible

# Get banned IPs from fail2ban (format as list, one per line)
BANNED_IPS_RAW=$(fail2ban-client status sshd | grep "Banned IP list" | cut -d':' -f2)
BANNED_IPS=$(echo "$BANNED_IPS_RAW" | tr -d '\t' | tr ' ' '\n' | grep -v '^$' | sed 's/^/- /')
BANNED_COUNT=$(fail2ban-client status sshd | grep "Currently banned" | awk '{print $3}')

# Get last week's bans from log
WEEK_AGO=$(date -d '7 days ago' '+%Y-%m-%d')
RECENT_BANS=$(grep "Ban " /var/log/fail2ban.log 2>/dev/null | awk -v week="$WEEK_AGO" '$1 >= week' | wc -l)

# Get unique IPs banned this week
UNIQUE_IPS=$(grep "Ban " /var/log/fail2ban.log 2>/dev/null | awk -v week="$WEEK_AGO" '$1 >= week' | awk '{print $7}' | sort -u | wc -l)

# Create email
SUBJECT="Weekly Security Report - $(hostname)"
FROM="${1:-fail2ban@$(hostname -f)}"
TO="${2:-root@$(hostname -f)}"

cat << EOF | /usr/bin/msmtp -t "$TO"
Subject: $SUBJECT
From: $FROM
To: $TO
Content-Type: text/plain; charset=UTF-8

=== WEEKLY FAIL2BAN SECURITY REPORT ===
Server: $(hostname -f)
Date: $(date)
Period: Last 7 days

=== CURRENT BAN STATUS ===
Currently banned IPs: $BANNED_COUNT

Banned IP list:
$BANNED_IPS

=== WEEKLY STATISTICS ===
Total ban events: $RECENT_BANS
Unique IPs banned: $UNIQUE_IPS

=== NOTES ===
- All bans are permanent (no unban unless manual)
- Bans occur after 10 failed login attempts within 24 hours
- To unban an IP manually: fail2ban-client set sshd unbanip <IP>

EOF
